services:
  mysql:
    image: mysql:8.4
    container_name: coffeeshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: coffeeshop
      MYSQL_USER: coffeeshop
      MYSQL_PASSWORD: coffeeshop
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: coffeeshop-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data: