spring:
  application:
    name: coffeeshop-order-systems

  datasource:
    url: jdbc:mysql://localhost:3306/coffeeshop
    username: coffeeshop
    password: coffeeshop
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always